spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false

logging:
  level:
    org.hibernate.SQL: info

jwt:
  secret: "testsecret_verylongrandomsecretstringwithatleast32bytesforhs256"
  expiration: 3600000
